### ISSUE TITLE
TI-level of Performance for Copying Cube Data

### ISSUE THREAD

**Issue by macsir** [cubewise-code/tm1py#102]
Hi, MariusWirtz
I have been learnt a lot for REST API usage from your code. Thanks.
Recently, I am thinking to use REST API to copy data between two same cubes with same dimensions/hierarchy/elements. I have finished the testing using tm1.Update function and works fine but the performance is not quite good. Is there a way to achieve similar TI-level performance of using exporting to a file and importing from the file to copy data from your point of view?
I am trying to use Cellset with MDX patching method to do that but the problem is with building a exact same generic MDX query on target cube. 
If you use hard-coded elements from each dimensions to build this target MDX, then it would be too long if there are many elements and dimensions. My goal is to have a generic dynamic MDX for Cellset to copy between cubes.
If you have any better idea, please let me know. Thanks.

**Comment by MariusWirtz** [comment]
Hi @macsir,

unfortunately, through the REST API you will not get to TI level performance yet.
With TM1 11, IBM made some improvements on how parallel REST write operations scale. I suppose there is more coming, but for the moment TI is the champion in terms of performance.

Here are some ideas to get more speed with your current approach:
- Is it given, that source and target dimensions are "in sync"? If yes and if you don't use zero suppression in the MDX Queries, you could do dynamic MDX expressions (or references or existing subsets) on rows and columns. Then you wouldn’t need to explicitly mention every element.

- If you do use zero suppression on the source view and you only want to write the zero suppressed result set, maybe you could look into using tuples on rows and columns on target MDX instead of sets.

- If in your setup you can assume that there are actually not many different cells between source and target, then you could also query the same slice from source and target, determine the differences (on the client side in like python or java) and then only write the cells that are actually different.

- If you got not enough CPUs available on the TM1 side you can also parallelize the write operations.

**Comment by macsir** [comment]
Hi, Marius
Thanks for your suggestion and I will look into them later. Reading from source and transferring small amount of data between source and target are not problems. It is just painful to write massive data into the target. If IBM won't give out better approach, I think I will end with using dynamic TI code to load source files.

**Comment by macsir** [comment]
Actually, it is not massive. I tested with a cube with MB level data and takes around 7 to 8 minutes for updating with tm1.Update function.
