### ISSUE TITLE
tm1.cubes.cells.write_value will not work with tm1s.cfg parameter EnableSandboxDimension=T

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/tm1py#136]
**Describe the bug**
If you put  EnableSandboxDimension=T than TM1 considers that as a first dimension of every cube.  Function tm1.cubes.cells.write_values does not work when using this paramterer.
Reading data from the cube (at least using tm1.cubes.cells.execute_mdx) still works.

And I'm able to write data when I  switch rhe parameter to EnableSandboxDimension=F.

cellset={}
cellset[('2019-05-04', 'FOOTBALL-EQ', 'RSU')]= 1
cellset[('2019-05-04', 'JORDAN-EQ', 'RSU')]= 2

tm1.cubes.cells.write_values('RSU Forecast', cellset)

**To Reproduce**
Test on simple cube with EnableSandboxDimension=T .

cellset={}
cellset[('2019-05-04', 'FOOTBALL-EQ', 'RSU')]= 1

tm1.cubes.cells.write_values('RSU Forecast', cellset)

**Expected behavior**
You will see the error like this:
TM1pyException: Text: {"error":{"code":"278","message":"'2019-05-04' can not be found in collection of type 'Element'."}} Status Code: 404 Reason: Not Found

**Version**
TM1py latest from PIP
TM1 Server Version: 11.4.00003.8

**Comment by lotsaram** [comment]
I am pretty sure that _**reading**_ works as expected because “BASE” is the default member of the Sandbox (virtual) dimension.

Probably the correct behaviour is to get the active sandbox and explicitly add it to the query (but only when sandbox as virtual dimension is switched on).

**Comment by 4rtem** [comment]
I tried to ass

> I am pretty sure that _**reading**_ works as expected because “BASE” is the default member of the Sandbox (virtual) dimension.
> 
> Probably the correct behaviour is to get the active sandbox and explicitly add it to the query (but only when sandbox as virtual dimension is switched on).

Hi @lotsaram , I tried to add "base" as the first element in the "coordinates' tupple. In that case I'm getting an error that "tupple" does not have correct number of members.

**Comment by MariusWirtz** [comment]
Hi @4rtem ,

the `write_values` method actually takes an optional third argument: `dimensions`.
For your code everything should work fine if you just add the `dimensions` argument to the function call and pass the actual dimension names of the cube (excluding the sandboxes dimension):


```
with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PASSWORD, ssl=SSL) as tm1:
    cellset = {
        ('Elem 1', 'Elem2', 'Elem4'): 1,
        ('Elem 1', 'Elem4', 'Elem3'): 3}
    tm1.cubes.cells.write_values('Cube1', cellset, dimensions=('dim1', 'dim2', 'dim3'))
```

On the TM1py side I think we need to enhance the `write_values` method. 

Currently if you do not pass that argument, TM1py will _(behind the scenes)_ ask what are the dimensions of the cube. 
If you have the `EnableSandboxDimension` parameter enabled, TM1 would return: `('Sandboxes', 'dim1', 'dim2', 'dim3')` to TM1py.
Then TM1py would 
- Either fail to make sense of the imcompatability of 3 elements in the tuple vs. 4 dimensions in the cube 
- Or if the tuples contain the sandbox name as the first argument TM1py would try to write to the Base element of the Sandbox dimension, with tuples like these:
`([Sandboxes].[Sandboxes].[Base], [dim1].[dim1].[Elem1], [dim2].[dim2].[Elem2], [dim3].[dim3].[Elem4]) : 1`
This would then fail, because TM1 does not support write operations, where the element from the Sandboxes dimension is referenced explicitly in the tuple.

I think the solution is:
When the dimensions argument is not passed to the `write_values` method and TM1 says that the first dimension of the Cube is called `Sandboxes`, then we need to drop that dimension and proceed.
