### ISSUE TITLE
Make calculations efficiently 

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#161]
Hello Marius,

I am facing some difficult related to speed performance.

When I want to make some calculation (e.g products), I usually do the following:

1 - Get a list (from mdx query) of products and Stores to iterate over.

2- Using the 'Multiprocessing' module, I make all the calculation product by product.

3- Then I write back the data to the cube using  `build_cellset_from_pandas_dataframe(df.astype(str))`

My structure is like this:

```
function1(x, y):

     md = "SELECT NON EMPTY " \
          "{[Date].[Total ]} *  {[Products].[" + str(y) + "]} on COLUMNS,  " \
          "NON EMPTY {[Demand].[Demand]} * {[Stores].[" + str(x) + "]} ON ROWS " 
          "FROM [EST_Gestão_Dados]"
....
....  # Data Manipulations + Calculations
....
    df = build_cellset_from_pandas_dataframe(df.astype(str))
    tm1.cubes.cells.write_values(
                        cube_name="ABC",
                        cellset_as_dict=df)

main( ):
        pool = mp.Pool(processes=3)

        for y, ar in dis.items():
            for x in ar:
                pool.apply_async(func=function, args=(x, y, tm1))

        # close the pool and wait for it to finish
        pool.close()
        pool.join()


if __name__ == '__main__':
    main()
```

Most of the calculations takes too long to run over all products (around 7000). 

1 - Is it efficient to make calculation like this ?

2 - This is a good format to write data back to the cube ?
`{('Total', '2019-01-06', '60290', 'Demand'): '219.28`

Thank you very much

**Comment by MariusWirtz** [comment]
Hi, 

generally, there are a few things to consider. The calculations inside python should all be fast!. If not, try to optimize them. In pandas there are a lot of things to consider when you need to be fast.

Typically, what slows you down is when you send too many (or inefficient) requests between python and TM1.
So in order to be fast, you need to keep the amount of requests at a minimum and you need to optimize your read and write queries. 

For the read queries, query only the information you need. Try to use one big query instead of multiple small ones and obviously your MDX Queries should be zero suppressed to leverage the zero-suppression feature in TM1.

For the write queries you should use the `write_values_through_cellset` method instead of the `write_values` method. It is significantly faster! Unfortunately, it is bit more tricky to use it (you need to provide an MDX that describes a slice in the cube and provide a list of values to populate the slice. More information in the docstring of the function).

When you write your data back to the cube you can do this multithreaded. This should give you another performance boost. 

Hope this helps.

P.S.
If you are looking for a more in-depth feedback on your TM1py scripts, you can get a touch with your local cubewise office. 

Cheers,

Marius

**Comment by kaleming** [comment]
Thank you very much Marius, It makes a lot of sense. 

Using `write_values_through_cellset` I noticed that CPU usage dropped significantly.

When you mentioned:

>  When you write your data back to the cube you can do this multithreaded. This should give you another performance boost.

Does it make sense using together with multiprocessing module ? Or should I use separately?

> Try to use one big query instead of multiple small ones and obviously your MDX Queries should be zero suppressed to leverage the zero-suppression feature in TM1.

What is best best way to split the data ?

The only way that I thought was:

1- Creating a mdx that filters only the products with data, saving into a list.

2- Then I split the list's size, creating a string that select each product (e.g [Products].[100], [Products].[200])

 ```
for i in list:
            a += f'[Products].[{i}],'

        a = a[:-1]
```
3- Finally I add this into the mdx:

```
mdx = "SELECT NON EMPTY " \
              "{TM1FILTERBYLEVEL( {TM1SUBSETALL( [Data] )}, 0)} on COLUMNS,  " \
              "{[Métricas Demanda].[Price} * {" + str(a) + "}  ON ROWS " \
              "FROM [EST_Data]"
```
* I also tried using 

`[Products].[100]:[Products].[1000]`

However it was not so efficient.


Thank you again.

**Comment by MariusWirtz** [comment]
A few things about your code:

Concatenating strings with `+=` is inefficient for technical reasons. Try to use the `",".join()` method instead. More details here:
https://docs.python-guide.org/writing/structure/#mutable-and-immutable-types

I noticed that your MDX query is not zero suppressed on the rows. Is this by design?

Regarding the implementation of the parallelization. I would need to know a bit more context to give you advice. This goes beyond the kind of question we would answer here on GitHub about TM1py. Feel free to contact me through the official cubewise channels.

**Comment by kaleming** [comment]
Thank you very much Marius four you advice. You helped me a lot.
I will make some tests first. 
If I have any trouble, I can contact cubewise channels for sure.
