### ISSUE TITLE
Enhancement - Support for Open ID

### ISSUE THREAD

**Issue by ianboltz** [cubewise-code/tm1py#184]
**Describe the bug**
Support for Open ID needed 

**To Reproduce**
Create TM1 model with Open ID security mode and TM1Py cannot connect

**Comment by pchuks23** [comment]
Hi,
Is there any update on this issue? Trying to connect to Azure AD (open ID connect) and facing the same issue. Please let me know if any updates.

Thanks

**Comment by MariusWirtz** [comment]
To be honest, it's no the highest item on our list currently. If you are using OpenID with CAM it should work though.

**Comment by rclapp** [comment]
I recommend that we push IBM to actually document the feature.

I have had a few discussions with IBM about it, they said since paw and Pax do not support it they don't offer public documentation.

Ryan Clapp
Sr. Manager
AWS FinTech

Sent from my mobile device

On Jul 12, 2020 1:13 PM, Marius Wirtz <notifications@github.com> wrote:

To be honest, it's no the highest item on our list currently. If you are using OpenID with CAM it should work though.

-

**Comment by tatwong** [comment]
We had a workaround on CAM side by setting up another authentication provider, can be Active Directory, OpenDJ, ApacheDS, etc.....
On Cognos Configuration side, make this new namespace Hidden or Invisible, while all other users are using OpenID or AzureAD to connect, end users do not have visibility to this hidden namespace at all.

**Comment by scrumthing** [comment]
Any plans to implement that in tm1py in the near future without the need for CAM?
