### ISSUE TITLE
TM1Service doesn't provide possibility to retain live connection

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/tm1py#190]
**Describe the bug**
Imagine a situation when connection is already established from outside of Python with known SessionID and TM1Service object is constructed with this SessionID.
Currently TM1Service implements a cleanup of connection in its __exit__ method, but for the approach described above the cleanup will close the connection. It would be nice to keep the connection live for instances like this.

**To Reproduce**
Allocate SessionID (token) outside Python, use it to initiate TM1Service. After TM1Service is discarded, the session is closed and SessionID can't be used anymore.

**Expected behavior**
A new switch in TM1Service configuration to retain connection.

**Version**
TM1py 1.3.1
TM1 Server Version: 11.6.00000.14

**Additional context**
NA

**Comment by pbuncik** [comment]
PS: this is not bug per se, but rather a feature request. As a temporary solution I can define a new descendant of TM1Service class that will redefine __exit__ method by own implementation.

**Comment by MariusWirtz** [comment]
Hi @pbuncik ,

We have a similar feature already implemented. Perhaps what you need intend to do can be accomplished with the `save_to_file` and `restore_from_file` methods
Here is a sample how to use them:
https://github.com/cubewise-code/tm1py-samples/blob/master/Administration/session_persist.py

https://github.com/cubewise-code/tm1py-samples/blob/master/Administration/session_reuse.py

does it work ?

Cheers,

Marius

**Comment by pbuncik** [comment]
Hi @MariusWirtz ,
I'm not convinced the approach proposed in session_persist.py would work. Here is why:
The idea is:
1) Open TM1 session outside TM1py in a web application (running on a web server). This is interactive application that uses the connection to query TM1 database frequently and also maintains the connection open for given user until the user logs out.
2) At some point of time we will launch a tool written in Python and utilizing TM1py.
3) The tool will reuse session open in step 1) by using session ID token that is transferred from the web application to the tool.
4) After the tool is finished it must retain the session open otherwise the user would experience logout from TM1 and would have to login again from within the web application again - this is unwanted behavior.

This approach is briefly what your second example is demonstrating - the session token is reused to hook-up to already connected session.
First example is demonstrating how to serialize the session into a file, but it doesn't solve problem with logging of the session during `__exit__` method call when TM1Session or RESTService objects are destroyed by garbage collector. At this point I need to avoid the call to logout the session to leave it open for the web application. The user should not be logged off and the call to the tool should be transparent to the user.
The issue I want

**Comment by MariusWirtz** [comment]
Hi @pbuncik ,

sorry for the late response.

What's the advantage of this new parameter `retain_connection` over instantiating the TM1Service without the with statement ?

The way I see this, in order to not invalidate the session, you could as well write it like this:

``` python

from TM1py import TM1Service

ADDRESS = '10.77.19.60'
PORT = 12354
USER = 'admin'
PASSWORD = 'apple'
SSL = True


tm1 = TM1Service(address=ADDRESS, port=PORT, user=USER, password=PASSWORD, ssl=SSL)

elements = tm1.dimensions.hierarchies.elements.get_element_names(
    dimension_name="d1",
    hierarchy_name="d1")

for element in elements:
    print(element)


```

**Comment by lotsaram** [comment]
Hi @MariusWirtz

My understanding of the use case is  we want to call tm1py from another application to do a specific task and we want to get the existing session token the other application and use that to authenticate the tm1py session rather than having the user need to re-enter credentials. This part we can already do. But when tm1py is finished we don’t want the session token invalidated as this leaves the original calling application without a connection. When tm1py exits we don’t want it to log out or close any sessions.

**Comment by pbuncik** [comment]
Hi @MariusWirtz - got your point, which is legit. When proposing this solution I was considering more robust approach to it as I thought it should be systemic solution embedded into the library rather than particular solution in one's code.
Should we use the solution you have proposed?

**Comment by rclapp** [comment]
Petr, you can do this already, tm1service and restservice take key word arguments. When you initialize a TM1 service object just pass it a session_id instead of a user name and password.

https://github.com/cubewise-code/tm1py/blob/fbc6393884ad140fea25c479930a84bd881c98d2/TM1py/Services/RESTService.py#L117


Ryan Clapp
AWS Business Systems
Sr. Manager

Sent from my mobile device

On Nov 25, 2019 12:50 AM, Petr Buncik <notifications@github.com> wrote:

Hi @MariusWirtz<https://github.com/MariusWirtz> - got your point, which is legit. When proposing this solution I was considering more robust approach to it as I thought it should be systemic solution embedded into the library rather than particular solution in one's code.
Should we use the solution you have proposed?

-
