### ISSUE TITLE
Testing the new release

### ISSUE THREAD

**Issue by dusherwo57** [cubewise-code/TM1py#21]
I'm having trouble migrating my simplistic (but useful) server query script.
`from TM1py.Utils import Utils
servers = Utils.get_all_servers_from_adminhost('')
print('Name','Port','HTTPPort','SSL',sep = '\t')
for s in servers:
     print (s.name, s.port_number, s.http_port_number,s.using_ssl, sep = '\t')
`
gives
`    servers = Utils.get_all_servers_from_adminhost('')
  File "D:\Users\dusherwo.INFOCAT-VG\AppData\Local\Programs\Python\Python36-32\lib\site-packages\TM1py\Utils\Utils.py", line 27, in get_all_servers_from_adminhost
    server = Server(server_as_dict)
TypeError: 'module' object is not callable`
Suggestions welcome.

**Comment by MariusWirtz** [comment]
Hi,
there is a small bug in the TM1py/Utils/Utils.py file.
The import at the top of the file should be absolute

it should be
`from TM1py.Objects.Server import Server`
instead of 
`from TM1py.Objects import Server`

I fixed it. I will push it with the next release. I think for know you have to update the file directly.

Thanks for catching that!

Marius

**Comment by dusherwo57** [comment]
Thanks - will update my copy.
Think the rest of the routines ported over fine but I'll do some more 
testing to confirm.



David Usherwood | Associate 
InfoCat, Riverside House, 27/29 Vauxhall Grove, London, SW8 1SY
p: 020 7735 7711 |  f: 020 7735 8811 
www.infocat.co.uk 
This message is private and confidential. If you have received this message in 
error, please notify us and remove it from your system.
InfoCat Ltd. is a limited company registered in England. Registered number: 
2843261. Registered office: 27-29 Vauxhall Grove, London, SW8 1SY.
