### ISSUE TITLE
Improve user class

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#224]
When I tried to analyze the users within an instance of TM1, I realized that certain properties are missing. Adding user type, is active and is enabled would be greatly appreciated.

**Comment by rclapp** [comment]
Have you tried combining the methods of the monitoring service with the security service?

Check out the methods and get_active_users and is_user_active

Since active or not is really a function of the current state of the server it likely does not make sense to add into the User object.

Enabled vs Disabled, would be a good edition though as long as it is exposed in the API

**Comment by rclapp** [comment]
I added an enabled property to the user class since I think we will get some use out of it too. 

https://github.com/cubewise-code/tm1py/pull/227

**Comment by scrumthing** [comment]
Thanks @rclapp 
The active property I mentioned only to have a complete picture. For my current use case I primarily need user type and is disabled. Trying to get a list of all users in every instance er cetera for license management purposes. The idea is to have an  ongoing monitoring of the users over all instances to check for under licensing. All of the necessary information is exposed via rest (except the read only user flag but there is a proper workaround via mdl.) and I already get the information. But for the future I would be great to include it In tm1py.
