### ISSUE TITLE
Get Campassport

### ISSUE THREAD

**Issue by dufaim** [cubewise-code/tm1py#234]
Hi Everyone 

I am trying to replace the current TM1 interface for users (Wokrspace / Perspectives / Applications) with an more friendly approach in html structured pages.
I wold like to start with a menu and some initial pages. But for the other pages I intend to set the url to current workspace/perspectives/applications pages, but without need to ask again for username and password.

I tried to get de campassport to pass trought the urls.

The code below not work for me, because there is no SSO in the system, we use autentication via Cognos Analytics.

"
_response = requests.get(gateway, auth=HttpNegotiateAuth(), verify=verify,
                                    params={"CAMNamespace": namespace})_
"

I had succes with the code below, but it works only in http IIS gateway, when it runs into https returns a forbidden status.

"
_url = "http://host/ibmcognos/bi/v1/login"_

_payload = "{\"parameters\":[{\"name\":\"CAMNamespace\",\"value\":\"NAMESPACE\"},{\"name\":\"h_CAM_action\",\"value\":\"logonAs\"},{\"name\":\"CAMUsername\",\"value\":\"USER\"},{\"name\":\"CAMPassword\",\"value\":\"PASS\"}]}"
headers = {
  'Accept': 'application/json',
  'Content-Type': 'application/json'
}_

_response = requests.request("POST", url, headers=headers, data = payload)_

_print(response)
print(response.cookies['cam_passport'])_
"

Can you have some idea of how can i get de campassport from my enviroment.

Thanks a lot for your attention.

Regards,

**Comment by cubewise-tryan** [comment]
Hi @dufaim,

I am not sure you can do it that way. There are ways to use the TM1Web URL API to show pages with credentials. I am not sure if it is possible with Workspace. Authentication is a complicated beast with TM1 because there are many options and ways it can be configured. 

The way you do it for CAM is to redirect the page to the gateway, the user logs in and then you receive the CAM passport.

We have a product (Apliqo UX https://code.cubewise.com/apliqoux) that handles all of this and also allows you to build dynamic pages. Under the hood it uses Canvas which allows you to use Angular components and JavaScript/HTML directly. I think using ApliqoUX will get you a better outcome faster than using the REST API directly with your own custom HTML/JavaScript. It does most of the heavy lifting for you so you can focus on the application rather than low level APIs.

Reach out to me directly via the contact page on the website linked above if you want more info. I will close this issue as it isn't related to TM1Py directly.
