### ISSUE TITLE
Modify clear_with_mdx or add second function

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#255]
The clear_with_mdx function is pretty helpful since there is no proper way of ZeroOut via Rest. 
But you have to add all dimensions for a proper zero out. Even if for most of the dimensions all n elements (tm1subsetall...tm1filterbylevel) are used. Could it be possible to add a function where you only define the mdx for the relevant dimensions. For all other dimensions a TM1FilterByLevel(Tm1SubsetAll(.. is added to the ROWS-section

**Comment by rkvinoth** [comment]
That is actually the easiest way especially when you use this method heavily at a variety of places. 
I would handle this at the client side and customize it as required because there are possibilities for human error where someone miss to provide `MDX` for a particular dimension and `TM1py` clears out all the leaf level.
Try exploring `mdxpy` which can come in handy for this kind of situation.

https://github.com/cubewise-code/mdxpy

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

I also think it's good to be explicit about what you want to zero out, but I imagine that other people would also appreciate this feature. Also, it would be in line with how the `pFilter` works in bedrock.
Any other opinions on that one?

How would you implement it? A second (optional) argument to the `clear_with_mdx` function? - Or do we add a dedicated function instead?

I see one problem though. It is not always obvious which dimensions are referenced and which ones aren't.
Just one example: When you apply the `GENERATE` method on a set, you can produce a set of a different dimension. So, parsing the MDX is not an option. IMO the only way to know which dimension is actually missing in your expression, it to execute the MDX and look at the Axis composition in the produced cellset. 
That would mean this function has a small disadvantage in terms of performance compared to the explicit `clear_with_mdx` function.

**Comment by MariusWirtz** [comment]
@scrumthing,

I added a new argument to the `clear_with_mdx` function: `all_leaves_as_default`
Please test the new function. You can install the branch with pip:
`pip install https://github.com/cubewise-code/tm1py/archive/feature/clear-with-mdx-all-leaves-as-default.zip --upgrade`

Unfortunately, we place high demands on the MDX that are passed to the functions. This is because we need to parse it to a certain extend and manipulate it: add the leaves of the missing dimensions.

You can read all the details here: #300 

What do you think about the name of the argument `all_leaves_as_default`? Is that indicative enough?

**Comment by MariusWirtz** [comment]
@scrumthing 

we implemented the new `clear` method in the `CellService`. It gives full flexibility without the need to parse or manipulate existing MDX queries.

You can use it like this:
`tm1.cells.clear(cube="Sales", product="{[Product].[ABC]}", time="{[Time].[2020].Children}")`

For the dimensions that you don't specify TM1py will use all leaves in the clearing MDX.
