### ISSUE TITLE
Get user available instance port

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#293]
Hello Marius,

I would like to ask you, if there is some straight-forward way to discover which instance's ports a user has access ?

For example:

I have 3 instances (port 13000 (gateway), 13001, 13002) on the same `address='localhost'`, but User_A only has permission to see cubes from port 13001 only.

Is there some way, using admin, to know which port number a user are able to access ?

Something like:
```
with TM1Service(address='localhost', port=13000, user='admin', password='apple', ssl=True) as tm1: 
    tm1.security.get_user_available_port(user_name='User_A')
```
`
    'User_A can access cubes from port (13000, 13001) only'`

**Comment by rclapp** [comment]
Just to clarify you want to check if a user has access to a certain TM1 Server?

If a user has no access are they still a named client on the server?

Could you explain a little more as to why determining access to a given instance is important?

Thanks,

Ryan Clapp

**Comment by kaleming** [comment]
Hi @rclapp, thanks for your reply.

Sorry, I didn't make myself very clear.

I just want to check in which TM1 server a certain user exists. I noticed there is a commit for a `user_exists` function. 

Maybe using this function (looping over all instances as admin), and check which TM1 Server ports this user exists, can be a way to solve this.

**Comment by rclapp** [comment]
Yes that would work. You could get all the instances on a given host, and for each of those login and check if a user exists.

If you use CAM security that can make it a little more difficult as users can be created at login time. So just because you exist, you might not have access.


Ryan Clapp
Sr. Manager
AWS FinTech

Sent from my mobile device

On Jul 22, 2020 6:14 PM, kaleming <notifications@github.com> wrote:

Hi @rclapp<https://github.com/rclapp>, thanks for your reply.

Sorry, I didn't make myself very clear.

I just want to check in which TM1 server a certain user exists. I noticed there is a commit for a user_exists function.

Maybe using this function (looping over all instances as admin), and check which TM1 Server ports this user exists, can be a way to solve this.

-

**Comment by kaleming** [comment]
Great, thank you again.
