### ISSUE TITLE
Tests need re-factoring

### ISSUE THREAD

**Issue by scrambldchannel** [cubewise-code/tm1py#301]
**Describe the bug**
The test suite could do with a bit of a tidy up. Currently, a lot of tests error, fail, warn or are skipped. Some objects are also left on the server which makes repeat running will throw more exceptions.  

**To Reproduce**
Running the test suite gives a number of errors, fails, warnings and skipped tests. Eg using pytest as a runner, do ```python -m pytest  Tests/*.py```

**Expected behavior**
Ideally, the test suite should run without any errors and clean up all the objects it creates. Perhaps we could add a bit more documentation on running the tests too. 

**Version**

TM1py master branch
TM1 Server Version: 11.3

**Additional context**

I discussed this briefly and made a start months ago but had to drop it and the codebase has moved on quite a bit anyway. I'm happy to pick this up (feel free to assign me @MariusWirtz-cubewise ).

I'm by no means a python testing expert but think there a few things we can try to improve:

* Fixing fails, errors etc - I realise many of these are down to my server version but would be good to skip them or expect the exception.
* Cleanly manage all the objects created on the test server using fixtures as much as possible
* Align the structure and conventions used in each different test file
* Adding a little entry in the README about testing or even a separate tutorial

Thinking even further ahead:

* Introduce an option to run a suite of mock tests to enable at least some testing when working offline

I'm going to try to work on small PRs rather than one monolith, all help gratefully received.

Note, I ran coverage and even skipping a few problematic tests it gave a score of 90%, which is a pretty good foundation I'd say.

Happy to receive any thoughts and ideas!

**Comment by MariusWirtz** [comment]
Thanks for bringing this topic up and volunteering to address it. Very much appreciated.
I agree with the 4 points you brought up.

For the server version, if something in TM1py doesn't work on a lower TM1 version we should add the new `require` decorator to the function.
Ideally, we also adjust the tests for those functions to not fail if version requirements are not met.

For me, all tests run successfully with version 11.7 with a few exceptions:
- in 11.7 and lower `test_create_chore_with_dst` fails due to an issue in TM1
- If the log filtering doesn't work it may be due to old/corrupt TM1 server log files in the log directory.
- I have seen occasional fails around chore time updates and process executions times (both are unproblematic TM1 issues IMO)


One thing I wanted to change in the test cases for a while is this : 
- map test modules 1 to 1 to the python classes. E.g. I think we should have one test class for the `SubsetService` class and another one for the `Subset` class.
I will take care of this after we addressed the more critical points that you mentioned.

I do like the idea to mock TM1 responses in tests. It would allow way faster and more granular testing.
I am not sure if it worth the effort though. Let's discuss this in another thread :)

Looking forward to your MR!

**Comment by scrambldchannel** [comment]
> For the server version, if something in TM1py doesn't work on a lower TM1 version we should add the new `require` decorator to the function.
> Ideally, we also adjust the tests for those functions to not fail if version requirements are not met.

Cool, I saw this had been added and it correctly raised an exception. I'll look at using that in the tests too.

> 
> For me, all tests run successfully with version 11.7 with a few exceptions:
> 
> * in 11.7 and lower `test_create_chore_with_dst` fails due to an issue in TM1
> * If the log filtering doesn't work it may be due to old/corrupt TM1 server log files in the log directory.
> * I have seen occasional fails around chore time updates and process executions times (both are unproblematic TM1 issues IMO)
> 

Great, I'm testing it on non-standard setup too - Linux with TM1 running in a VM, so think I'm seeing a lot of edge cases.

> One thing I wanted to change in the test cases for a while is this :
> 
> * map test modules 1 to 1 to the python classes. E.g. I think we should have one test class for the `SubsetService` class and another one for the `Subset` class.
>   I will take care of this after we addressed the more critical points that you mentioned.

Sounds good, on a similar note, I wondered whether it might make sense to rename the tests to make them more discoverable? Eg Tests/Annotation.py could become Tests/tests_annotation.py or something. It would simplify running tests with pytest and IDEs but I wasn't really sure of the implications of such a step change.  

> I do like the idea to mock TM1 responses in tests. It would allow way faster and more granular testing.
> I am not sure if it worth the effort though. Let's discuss this in another thread :)

Yeah, let's see, it's not a huge priority!

Cheers

**Comment by MariusWirtz** [comment]
Test refactoring is now completed.
