### ISSUE TITLE
TM1Py functions

### ISSUE THREAD

**Issue by Andy-Hofelmeyer** [cubewise-code/tm1py#347]
Hi there,
I am new with tm1py and just made my first python script to import data into Power BI.
Because I am not familiar with all the tm1py functions, I want to make use of the possibility to use the 'tab' tosee the functions.
See myprintscreen:
![image](https://user-images.githubusercontent.com/69905676/91166810-3af76080-e6d3-11ea-83b8-fb6a2615fd6f.png)

I installed jupyter notebook, upgraded tm1py but when I am using 'tab' after
**tm1.cubes.cells.**  or even after
**tm1.power_bi.**
nothing happened.

How can I see the functions which are available on tm1py?

Thanks in advance.

**Comment by scrumthing** [comment]
https://tm1py.readthedocs.io/en/latest/

**Comment by rkvinoth** [comment]
If you are a beginner and not sure about which function to execute then the best IDE that you should use is **PyCharm**.
Pycharm is very fast at _auto-completion_ because it will load all the libraries in memory.

**To answer your question:**
If you have already executed a cell and type further lines in that cell... then the use of 'tab' after a 'dot' won't work.

Basically what I'm saying is use a separate cell for creating the `tm1` object and type the remaining code in some other cell.

![image](https://user-images.githubusercontent.com/60260968/91171137-9e938500-e6f7-11ea-8e5b-e9fc5663b989.png)

**Comment by Andy-Hofelmeyer** [comment]
Thanks a lot everybody.
That helped alot.
