### ISSUE TITLE
Numeric Attribute Error

### ISSUE THREAD

**Issue by AliUgurGures** [cubewise-code/tm1py#356]
Hi All,

I am trying to write Tm1py code to Cube Sync between two instances. This code will sync data and metadata as well. My code is at the bottom;

``` python
from TM1py.Objects import Cube
from TM1py import TM1Service, DimensionService, CubeService

with TM1Service(address="localhost", port=8211, user="admin", password="apple", ssl=True) as tm1_source:
with TM1Service(address="localhost", port=12354, user="admin", password="apple", ssl=True) as tm1_target:

 #Retrive Sourcube dimensions
 SourceCube = tm1_source.cubes.get("_Sales")
 Dimlist = SourceCube.dimensions
 #Loop through dimension and create them in the target
 for dim in Dimlist:
     dimension = tm1_source.dimensions.get(dimension_name=dim)
     tm1_target.dimensions.update_or_create(dimension)

     #retrieve attributes
     mdx = f"""
         SELECT
         {{TM1SUBSETALL([{dimension.name}])}} ON ROWS,
         Tm1SubsetAll([}}ElementAttributes_{dimension.name}]) ON COLUMNS
         FROM [}}ElementAttributes_{dimension.name}]
         """

     values = tm1_source.cells.execute_mdx_values(mdx)
     tm1_target.cells.write_values_through_cellset(mdx, list(values))

 #Create or Update Cube on Target
 cube = Cube(name="_Sales", dimensions=['_Month', '_Product', '_Measure'], rules='')
 tm1_target.cubes.update_or_create(cube)

 #Retrive data from source cube
 mdx_data = """
   SELECT 
   {Tm1SubsetAll([_Product])} ON ROWS,
   {Tm1SubsetAll([_Month])} ON COLUMNS
   FROM [_Sales]
   WHERE ([_Measure].[Revenue])
   """
 #Write data to Target Cube
 values = tm1_source.cells.execute_mdx_values(mdx_data)
 tm1_target.cells.write_values_through_cellset(mdx_data, list(values))

```

Actually, It worked. But  I created an Numeric attribute for "_Product" dimension to see, If ıt moves the data from source to target(I try to write a generic code which will capture all the things like dimension,attributes, data etc.).

 And I got an error like;

TM1py.Exceptions.Exceptions.TM1pyRestException: Text: {"error":{"code":"143","message":"DataSpreadFailed"}} Status Code: 400 Reason: Bad Request Headers:

I think the error is about Numeric Attribute, because after I deleted it. Worked again. 

Maybe, I would be missing some points?

Thanks.

**Comment by MariusWirtz** [comment]
Hi @Bossua,

The REST API behaves a bit awkward wrt numeric attributes. I think this may cause the problem here.
If you query a numeric attribute that has a value of 0, the REST API (and consequently TM1py) will return `None`.

So this:
``` python
with TM1Service(**config["tm1srv01"]) as tm1:
    mdx = f"""
    SELECT
    {{Tm1SubsetAll([d1])}} ON ROWS,
    {{Tm1SubsetAll([}}ElementAttributes_d1])}} ON COLUMNS
    FROM [}}ElementAttributes_d1]
    """

    values = tm1.cells.execute_mdx_values(mdx)
    print(values)
```

produces this:
```
[None, None, None, 3, 4]
```

I think the error that you get comes from the fact you are trying to write the `None` back to TM1.
If this is in fact the problem, you can do two things.

1. Upgrade TM1. 
I don't get the error that you described on the latest release of TM1 11, with this code:

```
with TM1Service(**config["tm1srv01"]) as tm1:
    mdx = f"""
    SELECT
    {{Tm1SubsetAll([d1])}} ON ROWS,
    {{Tm1SubsetAll([}}ElementAttributes_d1])}} ON COLUMNS
    FROM [}}ElementAttributes_d1]
    """

    values = tm1.cells.execute_mdx_values(mdx)

    tm1.cells.write_values_through_cellset(mdx, values)

```

2. Explicitly convert None to 0 before sending the values to TM1.

``` python
with TM1Service(**config["tm1srv01"]) as tm1:
    mdx = f"""
    SELECT
    {{Tm1SubsetAll([d1])}} ON ROWS,
    {{Tm1SubsetAll([}}ElementAttributes_d1])}} ON COLUMNS
    FROM [}}ElementAttributes_d1]
    """

    values = tm1.cells.execute_mdx_values(mdx)
    values = [value or 0 for value in values]

    tm1.cells.write_values_through_cellset(mdx, values)
```

**Comment by Bossua** [comment]
Hi @MariusWirtz ,

You were right, If numeric attibute values are empty. They return None. 

After writing the code. I had another error which is because of the order attributes between source and target dimension.

So, we changed the attribute mdx little bit more.  We need to sort the attributes by  TM1Sort function as like at the bottom:

mdx = f"""
             SELECT
             {{TM1SUBSETALL([{dimension.name}])}} ON ROWS,
             TM1SORT({{TM1SUBSETALL([}}ElementAttributes_{dimension.name}])}}, ASC) ON COLUMNS
             FROM [}}ElementAttributes_{dimension.name}]
             """ 

Finally , It worked. Also, my idea is, I sync the dimensions, attributes(numeric and string) and data. 

What about rules? If I want to sync it to. Is there an option for that. Could you give some clue?

Thanks!

**Comment by MariusWirtz** [comment]
Hello @AliUgurGures,

here is a sample, that takes the rules of c1 and writes it as the rules of c2

``` python
from TM1py.Services import TM1Service

ADDRESS = "localhost"
PORT = 12354
USER = "admin"
PWD = "apple"
SSL = True

with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PWD, ssl=SSL) as tm1:
    cube = tm1.cubes.get("c1")

    rules = cube.rules

    other_cube = tm1.cubes.get("c2")

    other_cube.rules = rules
    
    tm1.cubes.update(other_cube)
```

hope this helps!

**Comment by AliUgurGures** [comment]
Hi Marius,

You helped more than enough.

Thank you.
