### ISSUE TITLE
deactivate_activate(func)

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#406]
Hi,

I’m using set_local_start_time to update the start time of a chore.
It worked with the chore deactivated, but not with the chore activated.

I was therefore checking out function deactivate_activate(func), docs state “Higher Order function to handle activation and deactivation of chores before updating them”.

I checked this function in ChoreService.py on github:
If I understand this correctly, the @deactivate_activate pulls the set_local_start_time through deactivate_activate function to deactivate/activate the chore when necessary. **Is that correct?**

However, since this was not working for me with chore activated, I checked ChoreService.py on a fresh installation of TM1py from this morning (1.5.0, via pip install), and I see that @deactivate_activate is missing there in ChoreService.py (in the line before set_local_start_time function) and it looks like I have and older version installed? I tried install –upgrade but it says that I’m already up-to-date (1.5.0). 
**What am I doing wrong?**

**Comment by MariusWirtz** [comment]
Hi @hermie64,

this was fixed in 0c25fd3e9a4db7f9e952d9766c6f8bd6b98ae1e3

You are right, that the fix is not included in the TM1py version 1.5. on PyPI.
Please upgrade to the master branch of TM1py like this:
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`

Sorry for the inconvenience. We will create an official release in the next weeks

**Comment by MariusWirtz** [comment]
> If I understand this correctly, the @deactivate_activate pulls the set_local_start_time through deactivate_activate function to deactivate/activate the chore when necessary. Is that correct?

Yes, that's correct. Some manipulations (e.g. set_local_start_time) can only be done to deactivated chores. 
Instead of writing the deactivation and reactivation inside every function of the `ChoreService` we created this decorator. If the decorator is attached to a function, the chore will be deactivated before the execution of the function and reactivated after the execution of the function (even if the function fails with an error).

**Comment by hermie64** [comment]
Hi @MariusWirtz,

You guys are responding really fast. Thanks for that!
I now works correctly.

Best, Herman
