### ISSUE TITLE
use case for transaction_log_delta_requests

### ISSUE THREAD

**Issue by macsir** [cubewise-code/tm1py#512]
Hi, @MariusWirtz 
I am curious about the use cases for the two functions. Could you explain them? Thanks.
def initialize_transaction_log_delta_requests(self, filter=None, **kwargs):
def execute_transaction_log_delta_request(self, **kwargs) -> Dict:

**Comment by MariusWirtz** [comment]
The TM1 REST API allows delta requests against the transaction log to query the latest changes (= all new changes since your last check).
Here is a [sample ](https://github.com/cubewise-code/tm1py-samples/blob/master/Administration/transactionlog_delta_requests.py)

This REST API functionality requires sensible management of the transaction log on the TM1 server.
We have seen cases of transaction log files > 100GB and the functionality breaks.

**Comment by macsir** [comment]
@MariusWirtz 
Thanks for the instructions. Yes, I got it run successfully. The thing is every time I need to initialize_transaction_log_delta_requests first before tracking. If I stopped for some time, will TM1 server remember where I stopped last time and push the transactions logs after exactly that point continuously if I run initialize_transaction_log_delta_requests to track again? Thanks.

**Comment by MariusWirtz** [comment]
Hi @macsir,

the initial request can be expensive in terms of performance.

Depending on your use case, you could deploy your python script as a service and have it running in the background all the time. Then it needs to do the initial request only when you restart the TM1 instance.

Feel free to contact me if you would like to discuss that option in more depth.

**Comment by macsir** [comment]
Hi @MariusWirtz  
Thanks for that. Understand.
