### ISSUE TITLE
Activate/Deactivate Chore

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#515]
When I Active or Deactivate a Chore, with:

c = tm1.chores.get(chore_name)
c.activate() (or c.deactivate())
tm1.chores.update(c)

and Chore is set to use "Local Server Time" (Arc: Daylight Savings Sensitive (Local Time)), the "Local Server Time" is also updated?
So for example local is 11:00:00 AM and UTC = 10:00:00, after activating or deactivating the Chore, local = 10:00:00 AM and UTC = 09:00:00.
This is not happening when using UTC time and is inconsistent with manually activating/deactivating a Chore.

Don't know if this is an issue with TM1 REST API or TM1Py.

**Comment by MariusWirtz** [comment]
Thanks for reporting this issue. Will test it and get back to you.

**Comment by MariusWirtz** [comment]
Hi @hermie64,

Strange. I was able to replicate the issue when the chore is saved in UTC time [image below].

When the chore is saved in local server time, the code you posted does not trigger a reschedule by one hour.
I'm on version 11.8.00300.33. Which version are you on?

![image](https://user-images.githubusercontent.com/15182131/112737283-99cad400-8f59-11eb-93dc-1f9613deae25.png)

**Comment by MariusWirtz** [comment]
Please install the fix-branch and check if the issue is resolved.

`pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/chore-tz-issue.zip --upgade`

**Comment by hermie64** [comment]
Hi @MariusWirtz,

I was on 11.6.00000.14 / 2.0.8 and also tested now on 11.8.00400.7 / 2.0.9.5 where I can confirm your findings: "_Strange. I was able to replicate the issue when the chore is saved in UTC time._"

I upgraded TM1py as suggested and tested again.

On 11.8.00400.7 / 2.0.9.5:
Looks OK now but I see one small issue, after activating/deactivating the Chore, the time no longer shows the original time, for example 11:00:00, but instead 11:00:01 (it's also in your screenshot by the way).

On 11.6.00000.14 / 2.0.8:
Same issue as before.

**Comment by MariusWirtz** [comment]
Hi @hermie64,

thanks for the confirmation. 

> W.t.t 11.8

I think this is an issue (or perhaps rather a hack?) in the TM1 Server. 
It seems like the server is rescheduling it by one second to avoid the full hour format (`2020-11-05T09:00:00+01:00`), as the one-sec rescheduling only happens when time is set to a full hour.
I will dig deeper into this, but I assume the one sec is not a showstopper for you and we can merge the MR for now.
Is that correct?

> W.r.t. 11.6

I think we must assume an issue in the TM1 server here. Since it's fixed in 11.8 I wouldn't try to create a workaround for TM1py.
Is that OK? Can you upgrade your instances to 11.8?

**Comment by hermie64** [comment]
Hi @MariusWirtz,

Re. 11.8: _...but I assume the one sec is not a showstopper for you and we can merge the MR for now.
Is that correct?_
Correct.

Re. 11.6: No problem.

Thanks!
