### ISSUE TITLE
Integrated Login - Mode 3

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#532]
Hi,

I am trying to accomplish the following:

1-) Supposing I have tm1 server installed on oracle cloud.

2-) An external user_A from Company_A wants to access to tm1 using tm1py with integrated Windows authentication.

3-) This user_A does not have access to oracle cloud, which means - Windows that tm1 server is installed does not have this user registered (either local or AD).

4-) Because Oracle cloud does not use Company_A Ldap server (users can't login to oracle cloud machines), I just use ETLdap to export users UniqueID from Company_A Ldap server to }ClientProperties cube.

I would like to know what is the prerequisites to establish connection to tm1 using tm1py integrated login ? Is it enough just match UniqueID of }ClientProperties cube ? Or it is necessary that Windows (that tm1 server is installed) also have this user registered ?

```
from TM1py import TM1Service
with TM1Service(address='168.138.xxx.xxx', 
                port='13000', 
                integrated_login=True, 
                #namespace=None,
                #integrated_login_domain='PLAN-DEM',
                    ssl=True) as tm1:
    server_name = tm1.server.get_server_name()

TM1pyRestException: Text: '' - Status Code: 401 - Reason: 'Unauthorized' - 
Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'WWW-Authenticate': 'Negotiate, Basic realm="TM1"'}
```

**Comment by rclapp** [comment]
This is less of a TM1py question, and more of a generic TM1 API question. I would reach out to IBM support for questions about integrated login support first.

From: kaleming ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Monday, April 19, 2021 at 7:37 AM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubewise-code/tm1py] Integrated Login - Mode 3 (#532)


Hi,

I am trying to accomplish the following:

1-) Supposing I have tm1 server installed on oracle cloud.

2-) An external user_A from Company_A wants to access to tm1 using tm1py with integrated Windows authentication.

3-) This user_A does not have access to oracle cloud, which means - Windows that tm1 server is installed does not have this user registered (either local or AD).

4-) Because Oracle cloud does not use Company_A Ldap server (users can't login to oracle cloud machines), I just use ETLdap to export users UniqueID from Company_A Ldap server to }ClientProperties cube.

I would like to know what is the prerequisites to establish connection to tm1 using tm1py integrated login ? Is it enough just match UniqueID of }ClientProperties cube ? Or it is necessary that Windows (that tm1 server is installed) also have this user registered ?

from TM1py import TM1Service

with TM1Service(address='168.138.xxx.xxx',

                port='13000',

                integrated_login=True,

                #namespace=None,

                #integrated_login_domain='PLAN-DEM',

                    ssl=True) as tm1:

    server_name = tm1.server.get_server_name()



TM1pyRestException: Text: '' - Status Code: 401 - Reason: 'Unauthorized' - Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'WWW-Authenticate': 'Negotiate, Basic realm="TM1"'}

**Comment by scrumthing** [comment]
I think that will not work since the tm1 server is not within the boundaries of your AD.

**Comment by zsoltmoravcsik** [comment]
It could work if you federate your AD eith the client AD or subtree of his
AD. It O would explore an OAuth provider solution and provide access with
that to the system. of course I am just brainstorming without exact use case

**Comment by kaleming** [comment]
Thanks for the replies.
I will have a look in how to federate my AD @zsoltmoravcsik. It is a good suggestion.
I've found [this documentation](https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/federatingADFS.htm) that maybe helps to accomplish it.
