### ISSUE TITLE
get_active_session_threads not working

### ISSUE THREAD

**Issue by macsir** [cubewise-code/tm1py#564]
**Describe the bug**
get_active_session_threads not returning anything even if there is a process running on the server. exclude_idle flag doesn't work either.

**Expected behavior**
It should return the active thread ID or session ID

**Additional context**
I tested the call " url = "/api/v1/ActiveSession/Threads?$filter=Function ne 'GET /api/v1/ActiveSession/Threads'"" and looks like it always return nothing. Is that due to my server version (11.8)? If removing **ActiveSession**, it only returns part of the sessions and threads.

**Comment by rclapp** [comment]
Are you an admin user? Non admin accounts can only see their own thread.

Sent from my mobile phone

On Jul 6, 2021 3:40 PM, tm1sir ***@***.***> wrote:

Describe the bug
get_active_session_threads not returning anything even if there is a process running on the server. exclude_idle flag doesn't work either.

Expected behavior
It should return the active thread ID or session ID

Additional context
I tested the call " url = "/api/v1/ActiveSession/Threads?$filter=Function ne 'GET /api/v1/ActiveSession/Threads'"" and looks like it always return nothing. Is that due to my server version (11.8)? If removing ActiveSession, it only returns part of the sessions and threads.

-

**Comment by macsir** [comment]
Hi, @rclapp 
Yes, I am using the admin account.

**Comment by MariusWirtz** [comment]
Hi @macsir,

the `get_active_session_threads` function only returns threads that are running in the scope of your current active session.
So anything that's executed by other users or by yourself in another session is excluded by design.

It is really only interesting if you are doing stuff asynchronously. E.g. execute a process without waiting for the response.

**Comment by macsir** [comment]
Thanks. Marius. Would it be useful to check if there is any session or thread running on the server? E.g. Just a simple check before running any other process to avoid potential lock contention?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MariusWirtz** [comment]
Agree. We are missing a function to get all threads that are not idle.

currently, you can only use the `get_threads` function and filter in python.
