### ISSUE TITLE
Custom process variables with formulas not represented

### ISSUE THREAD

**Issue by marfrit** [cubewise-code/TM1py#71]
Hello,

not yet sure if this an issue of the REST API or not - if I create a variable in a TM1 process with a formula, the variable is not represented in the process.variables array.

**Comment by MariusWirtz** [comment]
Hi,

Currently TM1py cannot handle processes that were generated through the wizard.
When I wrote the ProcessService initially (around 2015) these variables weren't fully supported by the REST API. I am not sure if they ever will be.

So far nobody complained about it. I guess people don’t miss this feature since generating TI processes with the wizard is generally unpopular in the TM1 community. 

If you need this feature, feel free to create a Merge Request 😊

**Comment by marfrit** [comment]
Hi, 
it's one of those things that are popular in sales pitches :) 
I just checked the variable types available and tried what happens if somebody writes a process, and, for whatever wicked reason, decides to add a formula-variable. If that's considered "wizardry", it's fine for me to add that to my documentation. The wizard is considered harmful where I am anyways.

I'm going to close this issue and if I'm ever to see someone actually using the "intuitive GUI" for processes, I might be tempted to create that merge request. Not holding my breath though.
