### ISSUE TITLE
Resave mdx view to native view

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#719]
**Describe what did you try to do with TM1py**
Is there a way to resave a mdx view to a native view?

The conversion would be for a simple mdx view without hierarchies
so that the view can be shared and run on the older TM1 client - Perspectives.

**Version**
- TM1py 1.9.1

**Comment by macsir** [comment]
As IBM is moving into MDX world, I don't think it worthwhile to provide such backward support. And as far as I know, it might not be possible to do so technically in Python as traditional views are written in C.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: cubewise-gng ***@***.***>
Sent: Wednesday, May 18, 2022 7:18:36 PM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubewise-code/tm1py] Resave mdx view to native view (Issue #719)


Describe what did you try to do with TM1py
Is there a way to resave a mdx view to a native view?

The conversion would be for a simple mdx view without hierarchies
so that the view can be shared and run on the older TM1 client - Perspectives.

Version

  *   TM1py 1.9.1
