### ISSUE TITLE
Understanding write cellsets

### ISSUE THREAD

**Issue by Akaori** [cubewise-code/TM1py#73]
Hello,

I am starting my journey into tm1py, however I`ve been facing difficulties to send data back to tm1.

For example, if I have a simple cube with 2 dimensions (Image 1) and want to write a data from a csv file or a pandas dataframe (image 4):

![cubos](https://user-images.githubusercontent.com/45232866/48842064-6145e900-ede7-11e8-971f-9f192664de2f.png)

Using this code it tooks more than 6 hours to write 16000 lines into the cube.
```
df = pd.read_csv("Dataframe.csv", encoding='utf-8')

with TM1Service(address="xxx", port="xxx", user="admin", password="xxx", namespace=None,
                ssl=True) as tm1:
    cellset = {}
    for index, row in df.iterrows():
        cellset[(row['GBL_Produto'], row['EST_Controle_Estoque_Metrica'])] = row['Value']
        tm1.cubes.cells.write_values('EST_Controle_Estoque', cellset)

```

However I saw samples using codes that says: _Read a csv file with ~ 1000000 lines and write the data to a cube_ and examples using `write_values_through_cellset ` function. But I didn`t understand exactly how to use these functions in this situation.

**Comment by MariusWirtz** [comment]
Hi @Akaori ,

there are two things you can improve in your code, that should scale up the performance massively.

1. instead of looping through the dataframe you could call the function `build_cellset_from_pandas_dataframe` to generate a cellset from the pandas dataframe. 
This function is optimized for performance.

2. in your code you are calling the write_values function for every row in the dataframe. Behind the scenes, this functions sends an HTTP request through the network to the TM1 server and waits for the response. In terms of performance, this is quite expensive.
Your code will be much faster if you populate the cellset first and then send it to TM1. Thus sending all changes in one batch.


Here is a working sample:

```
import pandas as pd

from TM1py import TM1Service
from TM1py.Utils.Utils import build_cellset_from_pandas_dataframe

with TM1Service(address='10.77.19.60', port=12354, user='admin', password='apple', ssl=True) as tm1:
    d = {'d1': pd.Series(["e1", "e2", "e1", "e1", "e3"]),
         'd2': pd.Series(["e1", "e1", "e2", "e1", "e2"]),
         "Values": pd.Series([0.5, 1.2, 0.4, 8.1, 5.4])}
    df = pd.DataFrame(d)
    cellset = build_cellset_from_pandas_dataframe(df)

    tm1.cubes.cells.write_values(
        cube_name="c1",
        cellset_as_dict=cellset)

```

![image](https://user-images.githubusercontent.com/15182131/48864919-592d7f80-edce-11e8-890c-f30e36ba9686.png)


If the performance is still not satisfying there are two more things you can look into:
1. The `write_values_through_cellset` function:
https://github.com/cubewise-code/TM1py-samples/blob/master/Load%20Data/cube%20to%20cube.py

2. Parallelizing the write operations
https://github.com/cubewise-code/TM1py-samples/blob/master/Update%20Cells/write%20data%20fast.py

Or you could use good old TI ;)

**Comment by Akaori** [comment]
Oh, after converting all the columns into string, it was possible to use the function.

**Comment by Akaori** [comment]
It works. Much faster than before.

Thank you !

**Comment by MariusWirtz** [comment]
You’re welcome
