### ISSUE TITLE
Python Script to Query Transaction Logs

### ISSUE THREAD

**Issue by CJRothman** [cubewise-code/tm1py#841]
**Describe what did you try to do with TM1py**
I have a script that queries the transaction logs by cube and time stamp but it is taking a long time. I only want to query it since midnight and the files in question are less than 1MB but there are other older transaction log files that are HUGE. My suspicion is that TM1Py is not using the time stamp to only look at files with names greater than tm1s20221208*.log for December 8. Assuming I'm correct, would it be possible to enhance the "tm1.server.get_transaction_log_entries" function to be selective?

<img width="740" alt="image" src="https://user-images.githubusercontent.com/44240381/206573180-8f157705-c53d-49f3-a4b9-27c5876c5f70.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/44240381/206573234-882aadae-ed3c-42f5-956b-d39a1671474d.png">

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
The "tm1.server.get_transaction_log_entries" function is taking a VERY long time.

**Version**
- TM1py [e.g. 1.9.1] 
- TM1 Server Version: [e.g. 2.0.9

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by rkvinoth** [comment]
It is selective, but the REST API way of querying transaction log is not as fast as querying through Architect client.
This is from my experience.

You could alternatively write some python script to handle the tm1s20***.log file directly instead of querying through TM1py. 

Just for fun - You gotta give a little thought to that function name.

**Comment by MariusWirtz** [comment]
@CJRothman,
TM1py doesn't actually look at the files! TM1py asks the TM1 server for the relevant entries.
I also think the TM1 server could be more efficient when searching for entries. Especially when TM1py passes a `since` filter. 
This is something you need to raise with the IBM TM1 server team.

I agree with @rkvinoth it may be more efficient to look at the tm1s logs with python directly.
Perhaps this is something @scrambldchannel has already included in https://github.com/scrambldchannel/tm1-file-tools?
