### ISSUE TITLE
Add boolean `re_authenticate` argument to `TM1Service`

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#855]
In cases where a connection is idle for a while _(e.g. TM1py waiting for a long rule change to compile)_, it can happen that the TM1py connection is closed on the server side due to the session timeout defined in TM1. In that case, TM1py raises a 401 error on the next function call.

In that case, it would be convenient if TM1py would attempt to re-authenticate (once) with the TM1 Server instead of raising the 401 error.

Potential names for the new argument:
- `re_authenticate`
- `re_authenticate_on_session_timeout`
- `re_authenticate_on_401`

Any additional thoughts or ideas on this feature request?

**Comment by macsir** [comment]
Would it be convenient to allow user to specify max attempts?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Marius Wirtz ***@***.***>
Sent: Friday, January 27, 2023 10:21:56 PM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubewise-code/tm1py] Add boolean `re_authenticate` argument to `TM1Service` (Issue #855)


In cases where a connection is idle for a while (e.g. TM1py waiting for a long rule change to compile), it can happen that the TM1py connection is closed on the server side due to the session timeout defined in TM1. In that case, TM1py raises a 401 error on the next function call.

In that case, it would be convenient if TM1py would attempt to re-authenticate (once) with the TM1 Server instead of raising the 401 error.

Potential names for the new argument:

  *   re_authenticate
  *   re_authenticate_on_session_timeout
  *   re_authenticate_on_401

Any additional thoughts or ideas on this feature request?

**Comment by MariusWirtz** [comment]
@macsir Would you put a max_attempts in a way that
- the re-authentication must work on the first attempt (otherwise 401 is raised)?
- or would you say the script can only re-authenticate once and not again 2hours later on another session timeout?

**Comment by Acteon-Jon** [comment]
Would a delay option be useful? re_authenticate_on_401, re_authenticate_delay

**Comment by macsir** [comment]
> @macsir Would you put a max_attempts in a way that
> 
> * the re-authentication must work on the first attempt (otherwise 401 is raised)?
> * or would you say the script can only re-authenticate once and not again 2hours later on another session timeout?

Hi, @MariusWirtz  I was on the second point initially but as any session is governed by the timeout settings and cleaned out eventually if being idle long enough, it is kind of useless to have this max attempts. 
Thanks for implementing this anyway.  👍
