### ISSUE TITLE
Feature request: The function power_bi.execute_view should internally use the optimized version for getting data, but still retain the same shape

### ISSUE THREAD

**Issue by Cubewise-gtejeda** [cubewise-code/tm1py#888]
When comparing cells.execute_mdx_csv(use_iterative_json=True) to power_bi.execute_view on a larger dataset, it shows an around 85% memory improvement when using execute_mdx_csv.  
The two dimensional cube used for this test had one measure on the column and 5 million rows. There was no data in the cube and no zero suppression had been applied.  
  
**power_bi.execute_view:**  
  
![image](https://user-images.githubusercontent.com/44591391/230210917-f366321e-6621-484e-9c24-192318030919.png)
  
  
**execute_mdx_csv(use_iterative_json=True):**  
  
![image](https://user-images.githubusercontent.com/44591391/230210943-6e298888-17ef-4959-8c1a-23b7ccf47d67.png)

**Comment by MariusWirtz** [comment]
https://github.com/cubewise-code/tm1py/pull/893 solves this.
When working with very large data sets, you can now use `execute_view_dataframe(..., shaped=True)` instead of `execute_view_dataframe_shaped`. 

You can also pass `use_iterative_json=True` or `use_blob=True` to the existing`tm1.cells.execute_view_dataframe_shaped` and `tm1.power_bi.execute_view` function. 
Please note that in this case, the resulting data frame will be similar but slightly different:
- types are inherited slightly differently
- empty rows are omitted by default (unless `skip_zeros=False` is passed)
- 0 values in cells instead of nan

Sample:

``` python
from TM1py import TM1Service

params = {
    "address": "",
    "port": 8010,
    "user": "admin",
    "password": "apple",
    "ssl": True
}

with TM1Service(**params) as tm1:
    df = tm1.power_bi.execute_view("Sales Cube", "Default", private=False)
    print(df.to_markdown())

    df = tm1.power_bi.execute_view("Sales Cube", "Default", private=False, use_iterative_json=True)
    print(df.to_markdown())

    df = tm1.power_bi.execute_view("Sales Cube", "Default", private=False, use_blob=True)
    print(df.to_markdown())

    df = tm1.power_bi.execute_view("Sales Cube", "Default", private=False, use_blob=True, skip_zeros=False)
    print(df.to_markdown())

```
