### ISSUE TITLE
TM1ProjectTask construct_body and dependencies

### ISSUE THREAD

**Issue by janus-t** [cubewise-code/tm1py#978]
In this [function](https://github.com/cubewise-code/tm1py/blob/ad37cdd4ca1b7c00df9d635604f2a4d52c7b19ef/TM1py/Objects/GitProject.py#L65), there is a little bit illogical approach with dependencies.

Everything works fine, if you manually add Processes('') around process. However, dependencies get lost because of rows 73 and 80 for chores and processes respectively, if you only use name of the chore or process.

I think it would make sense that dependencies are included whether you have Processes/Chores in front or not.

This is present in latest version 1.11.3.

**Comment by nicolasbisurgi** [comment]
Hi @janus-t 
Thanks for posting this. This is definitely not the intended behavior as how you put the Chore or Process should have no consequence on dependencies. This is happening due to the order of the IF statements in the construction of the ProjectTask. Once the IF statement of the dependency is last then the code works as expected regardless of the way you declare the Process or Chore.

```python
def construct_body(self) -> Dict:
        body = dict()

        if self.chore:
            if not self.chore.startswith("Chores('"):
                body = {
                    "Chore": f"Chores('{self.chore}')"
                }
            else:
                body["Chore"] = self.chore
        else:
            if not self.process.startswith("Processes('"):
                body = {
                    "Process": f"Processes('{self.process}')",
                }
            else:
                body["Process"] = self.process
            body.update({"Parameters": self.parameters})
        
        if self.dependencies:
            body["Dependencies"] = self.dependencies

        return body
```

Would you agree?
